// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.1
// source: grpc/consensus.proto

package consensus_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CriticalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lamport int32 `protobuf:"varint,1,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Id      int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CriticalRequest) Reset() {
	*x = CriticalRequest{}
	mi := &file_grpc_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalRequest) ProtoMessage() {}

func (x *CriticalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalRequest.ProtoReflect.Descriptor instead.
func (*CriticalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *CriticalRequest) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

func (x *CriticalRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CriticalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CriticalReply) Reset() {
	*x = CriticalReply{}
	mi := &file_grpc_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalReply) ProtoMessage() {}

func (x *CriticalReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalReply.ProtoReflect.Descriptor instead.
func (*CriticalReply) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{1}
}

type LamportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LamportRequest) Reset() {
	*x = LamportRequest{}
	mi := &file_grpc_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamportRequest) ProtoMessage() {}

func (x *LamportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamportRequest.ProtoReflect.Descriptor instead.
func (*LamportRequest) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{2}
}

type LamportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lamport int32 `protobuf:"varint,1,opt,name=lamport,proto3" json:"lamport,omitempty"`
}

func (x *LamportReply) Reset() {
	*x = LamportReply{}
	mi := &file_grpc_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamportReply) ProtoMessage() {}

func (x *LamportReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamportReply.ProtoReflect.Descriptor instead.
func (*LamportReply) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *LamportReply) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

var File_grpc_consensus_proto protoreflect.FileDescriptor

var file_grpc_consensus_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0f,
	0x0a, 0x0d, 0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x10, 0x0a, 0x0e, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x28, 0x0a, 0x0c, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x32, 0xa1, 0x01, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x49, 0x0a, 0x0f, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e,
	0x63, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x63, 0x72, 0x69, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x2e, 0x6c, 0x61, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x71, 0x5a, 0x6f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x54, 0x4d, 0x49, 0x54, 0x2f, 0x6d,
	0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x2d, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x64, 0x69, 0x73, 0x67, 0x6f, 0x2f,
	0x74, 0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x79, 0x2d, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x34,
	0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_consensus_proto_rawDescOnce sync.Once
	file_grpc_consensus_proto_rawDescData = file_grpc_consensus_proto_rawDesc
)

func file_grpc_consensus_proto_rawDescGZIP() []byte {
	file_grpc_consensus_proto_rawDescOnce.Do(func() {
		file_grpc_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_consensus_proto_rawDescData)
	})
	return file_grpc_consensus_proto_rawDescData
}

var file_grpc_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_consensus_proto_goTypes = []any{
	(*CriticalRequest)(nil), // 0: consensus.criticalRequest
	(*CriticalReply)(nil),   // 1: consensus.criticalReply
	(*LamportRequest)(nil),  // 2: consensus.lamportRequest
	(*LamportReply)(nil),    // 3: consensus.lamportReply
}
var file_grpc_consensus_proto_depIdxs = []int32{
	0, // 0: consensus.ConsensusService.CriticalSection:input_type -> consensus.criticalRequest
	2, // 1: consensus.ConsensusService.GetLamport:input_type -> consensus.lamportRequest
	1, // 2: consensus.ConsensusService.CriticalSection:output_type -> consensus.criticalReply
	3, // 3: consensus.ConsensusService.GetLamport:output_type -> consensus.lamportReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_consensus_proto_init() }
func file_grpc_consensus_proto_init() {
	if File_grpc_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_consensus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_consensus_proto_goTypes,
		DependencyIndexes: file_grpc_consensus_proto_depIdxs,
		MessageInfos:      file_grpc_consensus_proto_msgTypes,
	}.Build()
	File_grpc_consensus_proto = out.File
	file_grpc_consensus_proto_rawDesc = nil
	file_grpc_consensus_proto_goTypes = nil
	file_grpc_consensus_proto_depIdxs = nil
}
