// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: lamport.proto

package mandatory_assignment_3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LamportTimeStamp_GetClientMessage_FullMethodName = "/chittychat.lamportTimeStamp/GetClientMessage"
)

// LamportTimeStampClient is the client API for LamportTimeStamp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LamportTimeStampClient interface {
	GetClientMessage(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error)
}

type lamportTimeStampClient struct {
	cc grpc.ClientConnInterface
}

func NewLamportTimeStampClient(cc grpc.ClientConnInterface) LamportTimeStampClient {
	return &lamportTimeStampClient{cc}
}

func (c *lamportTimeStampClient) GetClientMessage(ctx context.Context, in *ParticipantRequest, opts ...grpc.CallOption) (*ParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParticipantResponse)
	err := c.cc.Invoke(ctx, LamportTimeStamp_GetClientMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LamportTimeStampServer is the server API for LamportTimeStamp service.
// All implementations must embed UnimplementedLamportTimeStampServer
// for forward compatibility.
type LamportTimeStampServer interface {
	GetClientMessage(context.Context, *ParticipantRequest) (*ParticipantResponse, error)
	mustEmbedUnimplementedLamportTimeStampServer()
}

// UnimplementedLamportTimeStampServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLamportTimeStampServer struct{}

func (UnimplementedLamportTimeStampServer) GetClientMessage(context.Context, *ParticipantRequest) (*ParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientMessage not implemented")
}
func (UnimplementedLamportTimeStampServer) mustEmbedUnimplementedLamportTimeStampServer() {}
func (UnimplementedLamportTimeStampServer) testEmbeddedByValue()                          {}

// UnsafeLamportTimeStampServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LamportTimeStampServer will
// result in compilation errors.
type UnsafeLamportTimeStampServer interface {
	mustEmbedUnimplementedLamportTimeStampServer()
}

func RegisterLamportTimeStampServer(s grpc.ServiceRegistrar, srv LamportTimeStampServer) {
	// If the following call pancis, it indicates UnimplementedLamportTimeStampServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LamportTimeStamp_ServiceDesc, srv)
}

func _LamportTimeStamp_GetClientMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LamportTimeStampServer).GetClientMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LamportTimeStamp_GetClientMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LamportTimeStampServer).GetClientMessage(ctx, req.(*ParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LamportTimeStamp_ServiceDesc is the grpc.ServiceDesc for LamportTimeStamp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LamportTimeStamp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chittychat.lamportTimeStamp",
	HandlerType: (*LamportTimeStampServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientMessage",
			Handler:    _LamportTimeStamp_GetClientMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lamport.proto",
}
